name: Build and Deploy to GitHub Pages
permissions:
  contents: write
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          yarn
          make build-example
          # 1. We prepare a clean deployment file
          mkdir deploy
          # 2. We move the examples into the deployment folder
          cp -r examples deploy/
          # 3. We create the .nojekyll file at the ROOT of this folder
          touch deploy/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: deploy # We deploy the content of 'deploy'
          clean: true # Very important to remove old Markdown files that break Jekyll
